name: Java CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean build test && ./gradlew clean
      - name: Build & Push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: 2467027/user-profile
          tag: ${GITHUB_REF##*/}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
